INSERT INTO REGISTER VALUES (1, 'Registro 1 de Gabriel', 1);
INSERT INTO REGISTER VALUES (2, 'Registro 2 de Gabriel', 1);
INSERT INTO REGISTER VALUES (3, 'Registro 1 de Marcos', 1);

INSERT INTO PERSON VALUES (1, 'Gabriel', 1);
INSERT INTO PERSON VALUES (2, 'Marcos', 2);

INSERT INTO BRANCH VALUES (1, 'Ramos Mejía');
INSERT INTO BRANCH VALUES (2, 'Haedo');