INSERT INTO REGISTER VALUES (NULL, 'Registro 1 de Gabriel', 1);
INSERT INTO REGISTER VALUES (NULL, 'Registro 2 de Gabriel', 1);
INSERT INTO REGISTER VALUES (NULL, 'Registro 1 de Marcos', 1);

INSERT INTO PERSON VALUES (NULL, 'Gabriel', 1);
INSERT INTO PERSON VALUES (NULL, 'Marcos', 2);

INSERT INTO BRANCH VALUES (NULL, 'Ramos Mejía');
INSERT INTO BRANCH VALUES (NULL, 'Haedo');