DROP TABLE IF EXISTS REGISTER;
CREATE TABLE REGISTER {
    REGISTER_ID INT AUTO_INCREMENT PRIMARY KEY,
    REGISTER_TEXT VARCHAR NOT NULL,
    PERSON_ID INT NOT NULL
}

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON {
    PERSON_ID INT AUTO_INCREMENT PRIMARY KEY,
    PERSON_NAME VARCHAR NOT NULL,
    BRANCH_ID INT NOT NULL
}

DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH {
    BRANCH_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRANCH_NAME VARCHAR NOT NULL
}